### ISSUE TITLE
Save State command to be deprecated

### ISSUE THREAD

**Issue by rtalintyre** [Azure/container-apps-deploy-action#53]
When running the action in our pipeline we receive the following message in the logs:

Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Does this command need to be updated?

**Comment by cormacpayne** [comment]
@rtalintyre Hey Robert, thanks for filing this issue -- this is a strange warning to receive during the execution of this GitHub Action since it's not using `save-state` command (or `set-output`, which is also mentioned) anywhere. Since this is a composite action that does reference other actions, it's possible that another action we're referencing is using `save-state` and having this warning propagated.

When you have the chance, would you mind providing some context around where in the logs this warning is being written? I'm curious which commands are being ran before and after it so we can pinpoint the culprit. Thanks in advance!

**Comment by rtalintyre** [comment]
Hello Cormac, thank you for the response. Here is a screenshot which may help:
![image](https://github.com/Azure/container-apps-deploy-action/assets/29194510/3c595700-491d-46fa-a004-4b3353a5be68)
and these are the commands just after:
![image](https://github.com/Azure/container-apps-deploy-action/assets/29194510/c9f6cbda-b784-4c00-b2ee-f966302540bb)
I've had to crop off some of the image so as to avoid sharing any sensitive information. I hope this helps, but if not let me know and I'll try and provide you more information.

**Comment by cormacpayne** [comment]
@rtalintyre Perfect, thanks Robert -- this confirms it's coming from the Docker GitHub Action we're using for authentication, which we have a [pull request](https://github.com/Azure/container-apps-deploy-action/pull/48) open for to resolve. Let me check back on this PR and why it hasn't been merged yet.

**Comment by rtalintyre** [comment]
@cormacpayne - looks like an approving review is needed to merge the PR. Thank you for the support - looks like bumping the docker version will resolve this issue 💯

**Comment by cormacpayne** [comment]
@rtalintyre OK this has been merged and `v1` has been updated to reflect this -- we should be good to go! :shipit:

**Comment by rtalintyre** [comment]
![image](https://github.com/Azure/container-apps-deploy-action/assets/29194510/cad30d74-a0e5-4db2-a464-d50ff12a6ee7)
Working great! @cormacpayne good job!
